image: hltcoe/concrete-python:4.13.3

stages:
  - build

variables:
  QLOOK: /home/concrete/.local/bin/qlook.py
  COMM_PATH: /builds/research/quicklime/agiga_dog-bites-man.concrete

test_python_2:
  stage: build
  script:
  - python setup.py install --user
  - $QLOOK --help
  - timeout --preserve-status 10s $QLOOK $COMM_PATH; RETVAL=$?; echo $RETVAL; if [ $RETVAL = 143 ]; then exit 0; else exit $RETVAL; fi
  tags:
  - docker

test_python_3:
  stage: build
  script:
  - python3.5 setup.py install --user
  - $QLOOK --help
  - timeout --preserve-status 10s $QLOOK $COMM_PATH; RETVAL=$?; echo $RETVAL; if [ $RETVAL = 143 ]; then exit 0; else exit $RETVAL; fi
  tags:
  - docker
