cache:
  paths:
  - node_modules/

variables:
  TIMEOUT_WRAPPER: /builds/research/quicklime/ci_timeout_wrapper.sh
  QLOOK: /home/concrete/.local/bin/qlook.py
  COMM_PATH: /builds/research/quicklime/agiga_dog-bites-man.concrete

test_js_with_grunt:
  image: node:latest
  script:
    # Force git to use https to work around JHU firewall settings,
    # as recommended here:
    #   https://github.com/npm/npm/issues/5257
    - 'git config --global url."https://github.com/".insteadOf git@github.com:'
    - 'git config --global url."https://".insteadOf git://'
    - npm install
    - node_modules/grunt/bin/grunt jshint
  tags:
  - docker

test_python_2:
  image: hltcoe/concrete-python:4.13.3
  script:
  - python setup.py install --user
  - $QLOOK --help
  - $TIMEOUT_WRAPPER 10s $QLOOK $COMM_PATH
  tags:
  - docker

test_python_3:
  image: hltcoe/concrete-python:4.13.3
  script:
  - python3.5 setup.py install --user
  - $QLOOK --help
  - $TIMEOUT_WRAPPER 10s $QLOOK $COMM_PATH
  tags:
  - docker
